### PR TITLE
Update items.php

### PR DESCRIPTION
**Pull request by aDaneInSpain**
This seems to fix the bug I emailed you about.

### CODE REVIEW

**Comment by yireo** [comment]
Hmm, the strange thing is that many are using SimpleLists on 3.4.1 already and experience no issue at all. So I'm still a bit puzzled as to how and why this occurs. I'll release a new version next week with this fix anyway. Many thanks.

**Comment by aDaneInSpain** [comment]
It could be a change in Joomla perhaps? Somehow it loaded the admin model and not the front end one.

**Comment by yireo** [comment]
It could be - I will dive into this to see what are the differences ...

**Comment by yireo** [comment]
The new release is now available. I will schedule some time in the near future to work a bit more on SimpleLists to see which code is outdated and which not. For now, it just works :) Let me know if it works for you too!

**Pull request merged**
